### ISSUE TITLE
Push latest changes for RN 0.40 to npm

### ISSUE THREAD

**Issue by joegoodall1** [yonahforst/react-native-heading#10]
Hi @yonahforst,

Referencing "react-native-heading": "1.0.0" in our package.json keeps returning files with the old headers for RN <0.40. To make it work with our project I've had to refer to the specific commit you've made with the headers changed for RN >=0.40.

Would it be possible to update npm with the changes you've made for RN 0.40 compatibility?

I've tested it and it all looks to be working well.

Thanks

**Comment by peterept** [comment]
When I `npm install --save react-native-heading` I am not getting the latest version with the RN >= 0.40 fix. What is wrong?

**Comment by peterept** [comment]
Oh, the latest version in NPM is 1.0.0 but the recent changes have not been put into a new version:

https://www.npmjs.com/package/react-native-heading

@yonahforst  could you please push the latest version ?

In the meantime, I will pull directly from master branch on this repo using:

`$ npm install --save git://github.com/yonahforst/react-native-heading.git`

**Comment by yonahforst** [comment]
hi @joegoodall1, hi @peterept 

I just pushed v1.1.0 to npm. thanks for staying on top of this!
