### ISSUE TITLE
Compile Android

### ISSUE THREAD

**Issue by gplopes** [yonahforst/react-native-heading#4]
I happy I found this plugin for Android/IOS. The iOS works fine but I cannot compile for Android.
 I'm getting this msg:

**error: constructor ReactNativeHeadingPackage in class ReactNativeHeadingPackage cannot be applied to given types;
              new ReactNativeHeadingPackage(),
              ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error**

I'm trying to search how to fix, although I don't have much experience with Java/Android. If you could have a look at it.

**Comment by Richou** [comment]
Hello,

This error will be fixed, if the author publish a new version of his module on npm, with the sources on master.

**Comment by gplopes** [comment]
Cool, that's what I'm hopping, haha.. I hope is checking the project. 👍

**Comment by yonahforst** [comment]
published v1.0.0. let me know if that fixes your problem

**Comment by gplopes** [comment]
@yonahforst it worked, thanks a lot.
