### ISSUE TITLE
Incorrect value when device is perpendicular to earth

### ISSUE THREAD

**Issue by zsajjad** [yonahforst/react-native-heading#5]
Appreciate your good work!
It works perfectly when device is parallel to earth's surface but when device is perpendicular to earth the it returns wrong values! Any idea how to get same value when device is perpendicular?

**Comment by yonahforst** [comment]
Hi there - I always understood it that it considers the top of the device the compass' 'needle point'. If that's true, then it makes sense that it would return incorrect values. That's what would happen if you held a compass the same way

**Comment by zsajjad** [comment]
Is there any way to calculate the angle when device is perpendicular to earth?

**Comment by yonahforst** [comment]
don't think so

**Comment by yonahforst** [comment]
addressed in #8. thanks @zsajjad !
