### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by gerardus1995** [yonahforst/react-native-heading#9]
For some reason i have installed and linked the module as you ask for and when i try to use it i says me like the import is undefined. I'm on react 0.40 and IOS. @yonahforst

**Comment by TanyaBob** [comment]
Had the same issue. Solved it by manually linking the library in Xcode: myProject>General>Linked Frameworks and Libraries, add items and than choose reachNativeHeading.

**Comment by stephanedemotte** [comment]
same here, when i try to add manually reactNativeHeading.a the build failed :/

**Comment by stephanedemotte** [comment]
downloaded version work, please bump the version :)

**Comment by TarasDumych** [comment]
build failed with errors
`clang: error: no such file or directory: '*/libReactNativeHeading.a'`

**Comment by yonahforst** [comment]
just bumped to version 1.1.0
